// src/app/layout.tsx

import { Metadata } from "next";
import GlobalStyle from "./styles/GlobalStyle"; // Ensure this path is correct
import StyledJsxRegistry from "../../registry"; // Correct the import path
import { LanguageProvider } from "../context/LanguageContext"; // Correct import for LanguageContext

// Import the Righteous font from Google using Next.js font optimization
import { Righteous } from 'next/font/google';

// Configure the Righteous font
const righteous = Righteous({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StyledJsxRegistry>
      <html lang="en" className={righteous.className}>
        <GlobalStyle /> {/* Global styles */}
        <body>
          <LanguageProvider>
            {/* Wrap the children with LanguageProvider for context */}
            {children}
          </LanguageProvider>
        </body>
      </html>
    </StyledJsxRegistry>
  );
}
