// src/app/layout.tsx or src/pages/_app.tsx (depending on your setup)

import type { Metadata } from "next";
import GlobalStyle from "./styles/GlobalStyle";
import StyledJsxRegistry from "../,,/../../registry";
import { LanguageProvider } from "../context/LanguageContext";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StyledJsxRegistry>
      <html lang="en">
        <GlobalStyle />
        <body>
          <LanguageProvider>
            {" "}
            {/* Wrap the children with LanguageProvider */}
            {children}
          </LanguageProvider>
        </body>
      </html>
    </StyledJsxRegistry>
  );
}
